name: simple-cprov2
version: 1.0
summary: This is a test snap
description: |
  This is an almost useless snap, apart from testing
confinement: strict
grade: stable

apps:
    simple:
        command: bin/simple

parts:
    simple:
        plugin: make
        source: .
